#!/usr/bin/env ruby

require 'thor'
require 'rockbuild'

cwd = File.expand_path('../', __FILE__)

# Require rockbuild
Dir["#{cwd}/../lib/**/*.rb"].each { |pkg| require pkg }

# Require all the packages
Dir["#{cwd}/../packages/**/*.rb"].each { |pkg| require pkg }

# Require all the projects
Dir["#{cwd}/../projects/**/*.rb"].each { |project| require project }

$stdout.sync = true

require "#{cwd}/../projects/demo_project"

#DemoProject.new.start

class RockbuildCLI < Thor
  desc 'projects', 'list available projects'
  def projects
    projs = Rockbuild::Project.descendants
    projs.each do |p|
      puts p.to_s
    end
  end
end

RockbuildCLI.start(ARGV)
